name: silo-build-image
on:
  workflow_dispatch:  # github页面手动触发
  push:
    branches:
      - 'master'
      - 'feature/1.3.5'  # 其他分支
    tags:
      - "v*.*"
env:
  IMAGE_NAME: verifier-silo  # 镜像名
  
jobs:
  push-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d-%H%M')"
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build && Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Verifier_Silo_Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.today }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
